import logging
import requests
from pydantic import BaseModel, Field

# Configure logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
if not logger.handlers:
    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(ch)

# --- Schemas ---

class AdvisorInput(BaseModel):
    alert_level: str = Field(..., description="Alert Level from Agent 5")
    warning_message: str = Field(..., description="Warning message from Agent 5")
    hotspot_zone: str = Field(None, description="Hotspot zone")
    people_count: int = Field(0, description="Total people count")
    stampede_risk: int = Field(0, description="Stampede risk score")

class AdvisorOutput(BaseModel):
    risk_summary: str = Field(..., description="LLM generated summary of the situation")
    safety_recommendations: str = Field(..., description="Recommended crowd control actions")
    incident_report: str = Field(..., description="Drafted incident report")

# --- Agent Implementation ---

class LLMSafetyAdvisorAgent:
    """
    Agent 6: LLM Safety Advisor Agent
    Uses local Ollama with Qwen3 to generate actionable safety recommendations,
    summaries, and incident reports based on telemetry data.
    """
    
    def __init__(self, ollama_url: str = "http://localhost:11434/api/generate", model_name: str = "llama3.1:8b"):
        """
        Initializes the LLM connection parameters.
        """
        self.ollama_url = ollama_url
        self.model_name = model_name

    def _build_prompt(self, data: AdvisorInput) -> str:
        """
        Constructs the context prompt for the LLM.
        """
        return f"""You are an expert Crowd Safety and Security Advisor.
Analyze the following telemetry from our crowd monitoring system:
- Current Alert Level: {data.alert_level}
- System Warning: {data.warning_message}
- Hotspot Zone: {data.hotspot_zone}
- Total People Count: {data.people_count}
- Stampede Risk Score: {data.stampede_risk}/100

Based on this data, provide your response in exactly 3 sections separated by "---":
1. Risk Summary: A concise 2-sentence summary of the current situation.
2. Safety Recommendations: 2-3 bullet points suggesting immediate crowd control actions.
3. Incident Report: A short drafted report log of the event.

Do not include any other conversational text.
"""

    def _call_ollama(self, prompt: str) -> str:
        """
        Makes a synchronous REST call to the local Ollama instance.
        """
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.2 # Keep it deterministic and professional
            }
        }
        
        try:
            logger.info(f"Calling Ollama model {self.model_name}...")
            response = requests.post(self.ollama_url, json=payload, timeout=30)
            response.raise_for_status()
            result = response.json()
            return result.get("response", "")
        except requests.exceptions.RequestException as e:
            logger.error(f"Ollama connection failed: {e}")
            return "---ERROR---\nCould not connect to local LLM for recommendations.\n---ERROR---"

    def _parse_llm_response(self, response_text: str, default_warning: str) -> AdvisorOutput:
        """
        Parses the text generated by the LLM into the required schema.
        """
        parts = [p.strip() for p in response_text.split("---")]
        
        if len(parts) >= 3:
            return AdvisorOutput(
                risk_summary=parts[0].replace("1. Risk Summary:", "").strip(),
                safety_recommendations=parts[1].replace("2. Safety Recommendations:", "").strip(),
                incident_report=parts[2].replace("3. Incident Report:", "").strip()
            )
        else:
            # Fallback if LLM doesn't follow formatting
            return AdvisorOutput(
                risk_summary=default_warning,
                safety_recommendations="Follow standard protocol.",
                incident_report="LLM formatting error. See raw logs."
            )

    def generate_advice(self, data: AdvisorInput) -> AdvisorOutput:
        """
        Executes the LLM advice generation workflow.
        """
        prompt = self._build_prompt(data)
        
        # For testing without a running Ollama server, we can mock the response here if needed,
        # but the code attempts the real REST API call.
        raw_response = self._call_ollama(prompt)
        
        parsed_output = self._parse_llm_response(raw_response, data.warning_message)
        logger.info("Safety Advisor generated recommendations successfully.")
        
        return parsed_output

# --- Example Usage ---
if __name__ == "__main__":
    agent = LLMSafetyAdvisorAgent()
    test_input = AdvisorInput(
        alert_level="RED", 
        warning_message="Zone C is experiencing critical density. Crowd diversion is recommended immediately.",
        hotspot_zone="Zone C",
        people_count=1450,
        stampede_risk=88
    )
    
    # NOTE: This will fail with connection error if Ollama is not actually running locally.
    output = agent.generate_advice(test_input)
    print(output.model_dump_json(indent=2))
